# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InternetConnection' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InternetConnection
pod 'ReachabilitySwift' , '4.3.0'
end
