# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackerChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HackerChat
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'

pod 'FirebaseUI/Storage'

pod 'PKHUD'

pod 'MessageKit'


end
