# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherHistory' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherHistory
  pod 'FSCalendar'
  pod 'Alamofire'
end
